-- MySQL Script generated by MySQL Workbench
-- Wed Jun  1 16:09:38 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`USERS` (
  `dni` VARCHAR(9) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `password` VARCHAR(70) NOT NULL,
  `phone` VARCHAR(13) NULL,
  `money` INT NULL DEFAULT 0,
  `date_of_birthday` DATETIME NOT NULL,
  `user_type` VARCHAR(25) NULL,
  PRIMARY KEY (`dni`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`SERVICE_OFFICE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`SERVICE_OFFICE` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(65) NOT NULL,
  `country` VARCHAR(65) NOT NULL DEFAULT 'SPAIN',
  `street` VARCHAR(250) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `city_town` VARCHAR(100) NULL,
  `block` INT NULL,
  `floor` INT NOT NULL,
  `ladder` INT NULL,
  `door` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`REAL_STATE_AGENT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`REAL_STATE_AGENT` (
  `user_dni` VARCHAR(9) NOT NULL,
  `weeks` INT NULL,
  `SERVICE_OFFICE_id` INT NOT NULL,
  PRIMARY KEY (`user_dni`),
  INDEX `fk_REAL_STATE_AGENT_SERVICE_OFFICE1_idx` (`SERVICE_OFFICE_id` ASC) VISIBLE,
  CONSTRAINT `fk_R_STATE_AGE_USER`
    FOREIGN KEY (`user_dni`)
    REFERENCES `proyecto_programacion_final`.`USERS` (`dni`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_R_STATE_AGE_S_OFFICE`
    FOREIGN KEY (`SERVICE_OFFICE_id`)
    REFERENCES `proyecto_programacion_final`.`SERVICE_OFFICE` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`PROPRIETOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`PROPRIETOR` (
  `user_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`user_dni`),
  CONSTRAINT `fk_PROPRIETOR_USERS`
    FOREIGN KEY (`user_dni`)
    REFERENCES `proyecto_programacion_final`.`USERS` (`dni`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`PROPERTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`PROPERTY` (
  `code` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `area` DECIMAL(7,2) NULL DEFAULT 0,
  `rentable` INT NOT NULL DEFAULT 0,
  `price` INT NULL DEFAULT 0,
  `description` VARCHAR(250) NULL,
  `property_type` VARCHAR(45) NOT NULL,
  `country` VARCHAR(65) NOT NULL DEFAULT 'SPAIN',
  `province` VARCHAR(100) NOT NULL,
  `city_town` VARCHAR(100) NULL,
  `street` VARCHAR(250) NOT NULL,
  `PROPRIETOR_user_dni` VARCHAR(9) NOT NULL,
  PRIMARY KEY (`code`),
  INDEX `fk_PROPERTY_PROPRIETOR` (`PROPRIETOR_dni` ASC) VISIBLE,
  CONSTRAINT `fk_PROPTR_PROPTY`
    FOREIGN KEY (`PROPRIETOR_user_dni`)
    REFERENCES `proyecto_programacion_final`.`PROPRIETOR` (`user_dni`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `valid_rentable` 
	CHECK (`rentable` = 0 OR `rentable` = 1))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`PHOTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`PHOTOS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `photo_file_path` VARCHAR(80) NULL,
  `PROPERTY_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `photo_name_file_UNIQUE` (`photo_file_path` ASC) VISIBLE,
  INDEX `fk_PHOTOS_PROPERTY1_idx` (`PROPERTY_code` ASC) VISIBLE,
  CONSTRAINT `fk_PHOTOS_PROPERTY`
    FOREIGN KEY (`PROPERTY_code`)
    REFERENCES `proyecto_programacion_final`.`PROPERTY` (`code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`PARKING_GARAGE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`PARKING_GARAGE` (
  `property_code` INT NOT NULL,
  `place` VARCHAR(4) NULL DEFAULT 'S/N',
  PRIMARY KEY (`property_code`),
  CONSTRAINT `fk_PARK_GARG_PROPT`
    FOREIGN KEY (`property_code`)
    REFERENCES `proyecto_programacion_final`.`PROPERTY` (`code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`BUILDING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`BUILDING` (
  `property_code` INT NOT NULL,
  `BUILD_CONDITIONS` VARCHAR(12) NULL DEFAULT 'ACCEPTABLE',
  `terrain` VARCHAR(15) NULL,
  `last_reform_date` TIMESTAMP NULL,
  `num_rooms` INT NULL DEFAULT 1,
  `num_baths` INT NULL DEFAULT 0,
  `num_bedrooms` INT NULL DEFAULT 0,
  `pool` INT NULL DEFAULT 0,
  `energy_certificate` VARCHAR(1) NULL,
  `building_type` VARCHAR(45) NOT NULL,
  `country` VARCHAR(65) NOT NULL DEFAULT 'SPAIN',
  `street` VARCHAR(250) NOT NULL,
  `province` VARCHAR(100) NOT NULL,
  `city_town` VARCHAR(100) NULL,
  `inc_parking_garage` INT NULL,
  PRIMARY KEY (`property_code`),
  CONSTRAINT `fk_BUILDING_PROPERTY`
    FOREIGN KEY (`property_code`)
    REFERENCES `proyecto_programacion_final`.`PROPERTY` (`code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BUILD_PARKGARG`
	FOREIGN KEY (`inc_parking_garage`)
    REFERENCES `PARKING_GARAGE` (`property_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `building_chk_1` 
	CHECK (((`patio` = 0) or (`patio` = 1))))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`FLAT`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`FLAT` (
  `property_code` INT NOT NULL,
  `block` INT NULL,
  `floor` INT NOT NULL DEFAULT 0,
  `ladder` INT NULL,
  `door` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`property_code`),
  CONSTRAINT `fk_FLAT_BUILDING`
    FOREIGN KEY (`property_code`)
    REFERENCES `proyecto_programacion_final`.`BUILDING` (`property_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`HOUSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`HOUSE` (
  `property_code` INT NOT NULL,
  `door` VARCHAR(5) NOT NULL,
  `patio` INT NULL DEFAULT 0,
  PRIMARY KEY (`property_code`),
  CONSTRAINT `fk_HOUSE_BUILDING`
    FOREIGN KEY (`property_code`)
    REFERENCES `proyecto_programacion_final`.`BUILDING` (`property_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`BLUEPRINTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`BLUEPRINTS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `blueprints_file_path` VARCHAR(250) NULL,
  `BUILDING_property_code` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_BLUEPRINTS_BUILDING1_idx` (`BUILDING_property_code` ASC) VISIBLE,
  CONSTRAINT `fk_BLUEPR_BUILDING`
    FOREIGN KEY (`BUILDING_property_code`)
    REFERENCES `proyecto_programacion_final`.`BUILDING` (`property_code`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proyecto_programacion_final`.`FAVS_USERS_PROPERTY`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyecto_programacion_final`.`FAVS_USERS_PROPERTY` (
  `USERS_dni` VARCHAR(9) NOT NULL,
  `PROPERTY_code` INT NOT NULL,
  PRIMARY KEY (`USERS_dni`, `PROPERTY_code`),
  INDEX `fk_USERS_has_PROPERTY_PROPERTY1_idx` (`PROPERTY_code` ASC) VISIBLE,
  INDEX `fk_USERS_has_PROPERTY_USERS1_idx` (`USERS_dni` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_FAVS`
    FOREIGN KEY (`USERusersS_dni`)
    REFERENCES `proyecto_programacion_final`.`USERS` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FAVS_PROPERTY`
    FOREIGN KEY (`PROPERTY_code`)
    REFERENCES `proyecto_programacion_final`.`PROPERTY` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
